#ifndef __TSS_CONSTANTS_H__
#define __TSS_CONSTANTS_H__

#define TSS_MAX_CMD_LEN 4096
#define TSS_MAX_SETTINGS_KEY_LEN 50

#define TSS_NUM_STREAM_SLOTS 16

#define TSS_BINARY_START_BYTE 0xF7
#define TSS_BINARY_HEADER_START_BYTE 0xF9

#define TSS_BINARY_READ_SETTINGS_START_BYTE 0xFA
#define TSS_BINARY_WRITE_SETTINGS_START_BYTE 0xFB

#define TSS_SETTING_SEPARATOR ';'

#define TSS_FILE_STREAMING_MAX_PACKET_SIZE 512
#define TSS_LOG_STREAMING_MAX_PACKET_SIZE 2048

#define TSS_OUTPUT_MODE_ASCII 1
#define TSS_OUTPUT_MODE_BINARY 2

#define TSS_LOG_START_EVENT_BUTTON 0
#define TSS_LOG_START_EVENT_ACCEL 1
#define TSS_LOG_START_EVENT_COMMAND_ONLY 2
#define TSS_LOG_START_EVENT_GPS_FIX 3
#define TSS_LOG_START_EVENT_ON_POWER 4

#define TSS_LOG_STOP_EVENT_BUTTON 0
#define TSS_LOG_STOP_EVENT_ACCEL 1
#define TSS_LOG_STOP_EVENT_COMMAND_ONLY 2
#define TSS_LOG_STOP_EVENT_DURATION 3
#define TSS_LOG_STOP_EVENT_CAPTURE_COUNT 4
#define TSS_LOG_STOP_EVENT_PERIOD 5

#define TSS_LOG_STYLE_CONTINUOUS 0
#define TSS_LOG_STYLE_PERIODIC 1

#define TSS_LOG_FOLDER_MODE_SESSION 0
#define TSS_LOG_FOLDER_MODE_DATETIME 1

#define TSS_LOG_FILE_MODE_APPEND 0
#define TSS_LOG_FILE_MODE_NEW 1

#define TSS_LOG_DATA_MODE_ASCII TSS_OUTPUT_MODE_ASCII
#define TSS_LOG_DATA_MODE_BINARY TSS_OUTPUT_MODE_BINARY

#define TSS_LOG_IMMEDIATE_OUTPUT_HEADER_MODE_MATCH 0
#define TSS_LOG_IMMEDIATE_OUTPUT_HEADER_MODE_ASCII TSS_OUTPUT_MODE_ASCII
#define TSS_LOG_IMMEDIATE_OUTPUT_HEADER_MODE_BINARY TSS_OUTPUT_MODE_BINARY

#define TSS_STREAMING_DATA_BATCH_COMMAND_NUM 84
#define TSS_STREAMING_FILE_READ_BYTES_COMMAND_NUM 177

#endif /* __TSS_CONSTANTS_H__ */