#ifndef __TSS_ERRORS_H__
#define __TSS_ERRORS_H__

#define TSS_ERR_NONE 0
#define TSS_SUCCESS TSS_ERR_NONE
#define TSS_ERR_READ -1
#define TSS_ERR_BUFFER_OVERFLOW -2
#define TSS_ERR_GET_SETTING_CALLBACK -3
#define TSS_ERR_SETTING_KEY_INVALID -4
#define TSS_ERR_SETTING_KEY_UNREGISTERED -5
#define TSS_ERR_UNEXPECTED_CHARACTER -6
#define TSS_ERR_CHECKSUM_MISMATCH -7
#define TSS_ERR_INVALID_READ_KEY -8
#define TSS_ERR_INVALID_WRITE_KEY -9
#define TSS_ERR_INVALID_STREAM_CALLBACK -10
#define TSS_ERR_INSUFFICIENT_BUFFER -11
#define TSS_ERR_UNEXPECTED_PACKET_LENGTH -12
#define TSS_ERR_READ_LEN -13
#define TSS_ERR_TIMEOUT -14
#define TSS_ERR_RESPONSE_NOT_FOUND -15
#define TSS_ERR_FAILED_START_LOGGING -16

#endif /* __TSS_ERRORS_H__ */